services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    environment:
      - DJANGO_ENV=production
    ports:
      - "8000:8000"
    restart: unless-stopped
    depends_on:
      - db
      - redis
  db:
    image: postgres:16
    env_file:
      .env
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: always
  redis:
    restart: always
    image: redis:7.0.5-alpine
    expose:
      - 6379
  celery:
    build:
      context: .
    restart: always
    command: poetry run celery -A CVProject worker --loglevel=info
    env_file:
     - .env
    environment:
      - DJANGO_ENV=production
    depends_on:
     - redis
     - db

volumes:
  postgres_data: