services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    environment:
      - DJANGO_ENV=production
    ports:
      - "8000:8000"
    restart: unless-stopped
    depends_on:
      - db
  db:
    image: postgres:16
    env_file:
      .env
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: always

volumes:
  postgres_data: